### ISSUE TITLE
RiseFM Radio Link not working

### ISSUE THREAD

**Issue by HexDevv** [Proximitynow19/Pulse#7]
Currently am working on a fix. Should be fixed by tonight :).

**Comment by HexDevv** [comment]
#8 Created a pull request. awaiting approval from prox pls <3

**Comment by HexDevv** [comment]
gonna reopen this so prox can accept the pull req

**Comment by HexDevv** [comment]
PROX FUCKING MERGE THE PULL REQ FFS IKPJOGNMRFDJIPBHNIOP[FDOIPJHFDJIPFD

**Comment by HexDevv** [comment]
PROX FUCKING MERGE THE PULL REQ FFS IKPJOGNMRFDJIPBHNIOP[FDOIPJHFDJIPFD

**Comment by HexDevv** [comment]
PROX FUCKING MERGE THE PULL REQ FFS IKPJOGNMRFDJIPBHNIOP[FDOIPJHFDJIPFD

**Comment by HexDevv** [comment]
PROX FUCKING MERGE THE PULL REQ FFS IKPJOGNMRFDJIPBHNIOP[FDOIPJHFDJIPFD

**Comment by HexDevv** [comment]
PROX FUCKING MERGE THE PULL REQ FFS IKPJOGNMRFDJIPBHNIOP[FDOIPJHFDJIPFD

**Comment by DefectivenessYT** [comment]
HEX CLOSE THIS SHIT

**Comment by HexDevv** [comment]
oki
